### ISSUE TITLE
The application crashes in some cases.

### ISSUE THREAD

**Issue by code-with-max** [cengiz-pz/godot-android-admob-plugin#17]
Hi
This is not a bug, but rather a feature that sometimes makes remote builds impossible.
I'll try to explain with an example:

This is your demo project, to which I added a completely empty scene:
In this case, the build will be successful and the game will start on the phone normally
![2024-08-31 22-21-13](https://github.com/user-attachments/assets/2166fe10-5c0f-4b27-8941-8a38cf094408)

But if I leave the tab active with an empty scene then the game will crash at the time of launch on the phone or emulator.
![2024-08-31 22-21-53](https://github.com/user-attachments/assets/76ef1f9c-c097-4c13-acab-307a592d0ffa)

I think this is due to using the get_edited_scene_root() method to set meta tags
![2024-08-31 22-23-10](https://github.com/user-attachments/assets/0757082e-6659-4dd2-9632-ca169094b722)

**Comment by cengiz-pz** [comment]
Hi @code-with-max, yes, this occurs because of the `get_edited_scene_root()` method.  If the current scene does not contain an Admob node, then the Android application will terminate since the Admob settings are missing.

Getting the Admob node from the project's main scene is a better solution, but needs a feasibility investigation and implementation effort.

**Comment by code-with-max** [comment]
Hi. I know :(
That's why I closed this issue.
I just hardcoded app ID when I use remote build. 
It's not exactly convenient, but it's the fastest solution. 
Thanks for the reply.
